# Generated by Django 4.1 on 2022-09-22 21:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserTravel', '0002_alter_avatar_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonio',
            name='fecha_publicacion',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 22, 18, 51, 11, 87122)),
        ),
    ]
