# Generated by Django 4.1 on 2022-09-23 11:29

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserTravel', '0004_alter_testimonio_fecha_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonio',
            name='fecha_publicacion',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 8, 29, 9, 129434)),
        ),
        migrations.AlterField(
            model_name='testimonio',
            name='texto',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
