# Generated by Django 4.1 on 2022-09-23 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserTravel', '0006_alter_testimonio_fecha_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonio',
            name='titulo',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='testimonio',
            name='fecha_publicacion',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 11, 37, 22, 146117)),
        ),
    ]
