# Generated by Django 4.1 on 2022-09-23 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserTravel', '0007_testimonio_titulo_alter_testimonio_fecha_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonio',
            name='fecha_publicacion',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 13, 19, 22, 13824)),
        ),
        migrations.AlterField(
            model_name='testimonio',
            name='titulo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
