# Generated by Django 4.1 on 2022-09-23 16:20

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserTravel', '0008_alter_testimonio_fecha_publicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonio',
            name='fecha_publicacion',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 13, 20, 3, 525641)),
        ),
        migrations.CreateModel(
            name='ComentarioTestimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', ckeditor.fields.RichTextField()),
                ('fecha_comentario', models.DateTimeField(default=datetime.datetime(2022, 9, 23, 13, 20, 3, 525641))),
                ('id_testimonio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserTravel.testimonio')),
                ('user_comentario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
