# Generated by Django 4.1 on 2022-09-24 20:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserTravel', '0010_alter_comentariotestimonio_fecha_comentario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentariotestimonio',
            name='fecha_comentario',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 24, 17, 53, 35, 509127)),
        ),
        migrations.AlterField(
            model_name='testimonio',
            name='fecha_publicacion',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 24, 17, 53, 35, 509127)),
        ),
    ]
