# Generated by Django 4.1 on 2022-09-26 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserTravel', '0012_alter_comentariotestimonio_fecha_comentario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentariotestimonio',
            name='fecha_comentario',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 8, 40, 30, 981679)),
        ),
        migrations.AlterField(
            model_name='testimonio',
            name='fecha_publicacion',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 8, 40, 30, 981679)),
        ),
    ]
