# Generated by Django 4.1 on 2022-09-27 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserTravel', '0015_alter_comentariotestimonio_fecha_comentario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentariotestimonio',
            name='fecha_comentario',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 12, 40, 9, 663916)),
        ),
        migrations.AlterField(
            model_name='testimonio',
            name='fecha_publicacion',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 12, 40, 9, 663916)),
        ),
    ]
