# Generated by Django 4.1 on 2022-09-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserTravel', '0017_alter_comentariotestimonio_fecha_comentario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentariotestimonio',
            name='fecha_comentario',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
