# Generated by Django 4.1 on 2022-09-27 16:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajeria',
            fields=[
                ('id_mensaje', models.AutoField(primary_key=True, serialize=False)),
                ('emisor', models.CharField(max_length=30)),
                ('reseptor', models.CharField(max_length=30)),
                ('mensaje', ckeditor.fields.RichTextField()),
                ('fecha_creacion_mensaje', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
