# Generated by Django 4.1 on 2022-09-27 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MsgTravel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajeria',
            name='fecha_creacion_mensaje',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 13, 42, 58, 382332)),
        ),
    ]
