# Generated by Django 4.1 on 2022-09-28 18:19

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MsgTravel', '0002_alter_mensajeria_fecha_creacion_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajeria',
            name='mensaje_reseptor',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='mensajeria',
            name='fecha_creacion_mensaje',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 28, 15, 19, 21, 638866)),
        ),
    ]
