# Generated by Django 4.1 on 2022-09-29 22:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MsgTravel', '0004_hilo_alter_mensajeria_fecha_creacion_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hilo',
            name='usuarios',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='mensajeria',
            name='fecha_creacion_mensaje',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 29, 19, 0, 43, 777716)),
        ),
    ]
