# Generated by Django 4.1 on 2022-09-29 23:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MsgTravel', '0005_alter_hilo_usuarios_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hilo',
            old_name='usuarios',
            new_name='emisor',
        ),
        migrations.AddField(
            model_name='hilo',
            name='reseptor',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mensajeria',
            name='fecha_creacion_mensaje',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 29, 20, 36, 59, 213714)),
        ),
    ]
