# Generated by Django 4.1 on 2022-09-30 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MsgTravel', '0006_rename_usuarios_hilo_emisor_hilo_reseptor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajeria',
            name='fecha_creacion_mensaje',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 8, 45, 22, 756084)),
        ),
    ]
