# Generated by Django 4.1 on 2022-09-30 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MsgTravel', '0010_alter_mensajeria_fecha_creacion_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hilo',
            name='reseptor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mensajeria',
            name='fecha_creacion_mensaje',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 8, 58, 41, 446065)),
        ),
    ]
