# Generated by Django 4.1 on 2022-09-30 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MsgTravel', '0011_alter_hilo_reseptor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajeria',
            name='fecha_creacion_mensaje',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 11, 15, 59, 910259)),
        ),
    ]
