# Generated by Django 4.1 on 2022-09-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MsgTravel', '0012_alter_mensajeria_fecha_creacion_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajeria',
            name='fecha_creacion_mensaje',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
