# Generated by Django 4.1 on 2022-10-01 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MsgTravel', '0013_alter_mensajeria_fecha_creacion_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hilo',
            name='emisor',
            field=models.CharField(max_length=50),
        ),
    ]
