# Generated by Django 4.1 on 2022-09-21 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NombreDestino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateField()),
                ('fecha_regreso', models.DateField()),
                ('num_personas', models.IntegerField()),
                ('destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppTravel.nombredestino')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NombreHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreh', models.CharField(max_length=40)),
                ('destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppTravel.nombredestino')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_personas', models.IntegerField()),
                ('dia_entrada', models.DateField()),
                ('dia_salida', models.DateField()),
                ('nombreH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppTravel.nombrehotel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
